import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseBoard,limits,move,won} from '../engine.js';
const read=p=>JSON.parse(readFileSync(p,'utf8'));
test('target reaches exit in one continuous move',()=>{const cars=parseBoard(read('data/0.json')[0][1]);assert.equal(won(cars),false);assert.deepEqual(limits(cars,'A'),{min:0,max:4});assert.equal(move(cars,'A',4),true);assert.equal(won(cars),true);assert.equal(move(cars,'A',5),false)});
test('cars cannot overlap, leave board, move diagonally or pass through a blocker',()=>{const cars=parseBoard(read('data/0.json')[1][1]);assert.deepEqual(limits(cars,'A'),{min:0,max:0});assert.equal(move(cars,'A',4),false);assert.equal(move(cars,'B',-1),false);assert.equal(move(cars,'B',1.5),false);assert.equal(move(cars,'B',3),true);assert.equal(move(cars,'A',4),true);assert.equal(won(cars),true)});
test('all exported puzzles have valid geometry and difficulty ranges',()=>{const m=read('data/manifest.json');let count=0;for(let n=0;n<Math.ceil(m.total/m.chunkSize);n++){for(const [minimum,board] of read(`data/${n}.json`)){count++;assert.equal(board.length,36);const cars=parseBoard(board);assert.ok(cars.some(c=>c.id==='A'&&c.horizontal&&c.y===2&&c.length===2));let cells=Array(36).fill('o');for(const c of cars){assert.ok(c.length===2||c.length===3);for(let i=0;i<c.length;i++){let x=c.x+(c.horizontal?i:0),y=c.y+(c.horizontal?0:i);assert.ok(x<6&&y<6);assert.equal(cells[y*6+x],'o');cells[y*6+x]=c.id;}}assert.equal(cells.join(''),board);const b=m.bands.find(b=>count>=b.start&&count<=b.end);assert.ok(minimum>=b.min&&minimum<=b.max);}}assert.equal(count,m.total)});
test('BFS independently reproduces source minimum moves on representative puzzles',()=>{for(const sample of read('tests/fixtures.json')){const initial=parseBoard(sample.board);let queue=[[initial,0]],seen=new Set(),answer;for(let head=0;head<queue.length;head++){const [cars,d]=queue[head];if(won(cars)){answer=d;break;}for(const c of cars){const bounds=limits(cars,c.id);for(let p=bounds.min;p<=bounds.max;p++){const next=cars.map(c=>({...c}));if(!move(next,c.id,p))continue;const key=next.map(c=>c.horizontal?c.x:c.y).join(',');if(!seen.has(key)){seen.add(key);queue.push([next,d+1]);}}}}assert.equal(answer,sample.expected)}});
